/**
 * This file is auto-generated by scripts/generate-examples-md.cjs.
 * Do not edit manually.
 */
import type { ExampleResult } from './types';
import { runDevboxFromBlueprintLifecycleExample } from './devbox-from-blueprint-lifecycle';
import { runDevboxSnapshotResumeExample } from './devbox-snapshot-resume';
import { runMcpGithubToolsExample } from './mcp-github-tools';

export interface ExampleRegistryEntry {
  slug: string;
  title: string;
  fileName: string;
  requiredEnv: string[];
  run: (options?: any) => Promise<ExampleResult>;
}

export const exampleRegistry: ExampleRegistryEntry[] = [
  {
    slug: 'devbox-from-blueprint-lifecycle',
    title: 'Devbox From Blueprint (Run Command, Shutdown)',
    fileName: 'devbox-from-blueprint-lifecycle.ts',
    requiredEnv: ['RUNLOOP_API_KEY'],
    run: runDevboxFromBlueprintLifecycleExample,
  },
  {
    slug: 'devbox-snapshot-resume',
    title: 'Devbox Snapshot and Resume',
    fileName: 'devbox-snapshot-resume.ts',
    requiredEnv: ['RUNLOOP_API_KEY'],
    run: runDevboxSnapshotResumeExample,
  },
  {
    slug: 'mcp-github-tools',
    title: 'MCP Hub + Claude Code + GitHub',
    fileName: 'mcp-github-tools.ts',
    requiredEnv: ['RUNLOOP_API_KEY', 'GITHUB_TOKEN', 'ANTHROPIC_API_KEY'],
    run: runMcpGithubToolsExample,
  },
];
