/**
 * This file is auto-generated by scripts/generate-examples-md.cjs.
 * Do not edit manually.
 */
import type { ExampleResult } from './types';
import { runDevboxFromBlueprintLifecycleExample } from './devbox-from-blueprint-lifecycle';
import { runMcpGithubToolsExample } from './mcp-github-tools';

export interface ExampleRegistryEntry {
  slug: string;
  title: string;
  fileName: string;
  live: boolean;
  requiredEnv: string[];
  run: (options?: any) => Promise<ExampleResult>;
}

export const exampleRegistry: ExampleRegistryEntry[] = [
  {
    slug: 'devbox-from-blueprint-lifecycle',
    title: "Devbox From Blueprint (Run Command, Shutdown)",
    fileName: 'devbox-from-blueprint-lifecycle.ts',
    live: true,
    requiredEnv: ['RUNLOOP_API_KEY'],
    run: runDevboxFromBlueprintLifecycleExample,
  },
  {
    slug: 'mcp-github-tools',
    title: "MCP Hub + Claude Code + GitHub",
    fileName: 'mcp-github-tools.ts',
    live: true,
    requiredEnv: ['RUNLOOP_API_KEY', 'GITHUB_TOKEN', 'ANTHROPIC_API_KEY'],
    run: runMcpGithubToolsExample,
  },
];
