/**
 * This file is auto-generated by scripts/generate-examples-md.cjs.
 * Do not edit manually.
 */
import type { ExampleResult } from './types';
import { runBlueprintWithBuildContextExample } from './blueprint-with-build-context';
import { runDevboxFromBlueprintLifecycleExample } from './devbox-from-blueprint-lifecycle';
import { runDevboxMountsExample } from './devbox-mounts';
import { runDevboxSnapshotsExample } from './devbox-snapshots';
import { runDevboxTunnelExample } from './devbox-tunnel';
import { runMcpGithubToolsExample } from './mcp-github-tools';
import { runSecretsWithDevboxExample } from './secrets-with-devbox';

export interface ExampleRegistryEntry {
  slug: string;
  title: string;
  fileName: string;
  requiredEnv: string[];
  run: (options?: any) => Promise<ExampleResult>;
}

export const exampleRegistry: ExampleRegistryEntry[] = [
  {
    slug: 'blueprint-with-build-context',
    title: 'Blueprint with Build Context',
    fileName: 'blueprint-with-build-context.ts',
    requiredEnv: ['RUNLOOP_API_KEY'],
    run: runBlueprintWithBuildContextExample,
  },
  {
    slug: 'devbox-from-blueprint-lifecycle',
    title: 'Devbox From Blueprint (Run Command, Shutdown)',
    fileName: 'devbox-from-blueprint-lifecycle.ts',
    requiredEnv: ['RUNLOOP_API_KEY'],
    run: runDevboxFromBlueprintLifecycleExample,
  },
  {
    slug: 'devbox-mounts',
    title: 'Devbox Mounts (Agent, Code, Object)',
    fileName: 'devbox-mounts.ts',
    requiredEnv: ['RUNLOOP_API_KEY', 'ANTHROPIC_API_KEY'],
    run: runDevboxMountsExample,
  },
  {
    slug: 'devbox-snapshots',
    title: 'Devbox Snapshots (Suspend, Resume, Restore, Delete)',
    fileName: 'devbox-snapshots.ts',
    requiredEnv: ['RUNLOOP_API_KEY'],
    run: runDevboxSnapshotsExample,
  },
  {
    slug: 'devbox-tunnel',
    title: 'Devbox Tunnel (HTTP Server Access)',
    fileName: 'devbox-tunnel.ts',
    requiredEnv: ['RUNLOOP_API_KEY'],
    run: runDevboxTunnelExample,
  },
  {
    slug: 'mcp-github-tools',
    title: 'MCP Hub + Claude Code + GitHub',
    fileName: 'mcp-github-tools.ts',
    requiredEnv: ['RUNLOOP_API_KEY', 'GITHUB_TOKEN', 'ANTHROPIC_API_KEY'],
    run: runMcpGithubToolsExample,
  },
  {
    slug: 'secrets-with-devbox',
    title: 'Secrets with Devbox and Agent Gateway',
    fileName: 'secrets-with-devbox.ts',
    requiredEnv: ['RUNLOOP_API_KEY'],
    run: runSecretsWithDevboxExample,
  },
];
