name: Generate Tools Definitions

on:
  push:
    branches:
      - 'next'
  workflow_dispatch:

jobs:
  generate-schema:
    name: Generate Zod Schema from OpenAPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get OpenAPI spec URL
        id: get-spec-url
        uses: mikefarah/yq@master
        with:
          cmd: yq '.openapi_spec_url' .stats.yml

      - name: Fetch OpenAPI spec
        run: |
          curl -o openapi-spec.json "${{ steps.get-spec-url.outputs.result }}"

      - name: Generate Zod schema
        run: |
          npx json-schema-to-zod openapi-spec.json > src/lib/zod.ts

      - name: Run post-processing script
        run: ./bin/generate-tools-defs

      - name: Check for changes
        id: check-changes
        run: |
          git diff --quiet src/ || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add src/
          git commit -m "chore: <your commit message>"
          git push
